tedhiyye_portal_cbar/Controllers/InfoController.cs
using tedhiyye_portal_cbar.Models;
using tedhiyye_portal_shared;
using tedhiyye_portal_shared.Domains;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using tedhiyye_portal_cbar;

namespace tedhiyye_portal_cbar.Controllers
{
    public class InfoController : Controller
    {
        public ActionResult Downloads(int id, int? department)
        {
            int? userId = HttpContext.Session.GetInt32("UserId") as int?;
            if (userId == null)
            {
                var path = HttpContext.Request.Path;
                var query = HttpContext.Request.QueryString;
                var pathAndQuery = path + query;
                return RedirectToAction("Login", "Home", new { ReturnUrl = pathAndQuery });
            }
            int group_id = id;
            ViewBag.Title = "Yükləmələr";
            //if (group_id == 2)
            //    ViewBag.Title = "Hesabat Formaları";
            //else
            //if (group_id == 3)
            //    ViewBag.Title = "Təlimatlar normativ-hüquqi baza";
            //else
            if (group_id == 4)
                ViewBag.Title = "İstifadəçi təlimatı";

            var DepartmentItems = DBCBAR.GetDepartments();
            ViewBag.DepartmentsList = new SelectList(
                DepartmentItems,
                "Value",
                "Text",
                department);
            var downloads = DBCBAR.GetDownloads(group_id, department);
            ViewBag.ShowDepartments = (group_id != 4);
            return View(downloads);
        }

        public ActionResult CheckRules(int? reportFileType, int? Status)
        {
            int? userId = HttpContext.Session.GetInt32("UserId") as int?;
            if (userId == null)
            {
                return RedirectToAction("Login", "Home", new { ReturnUrl = HttpContext.Request.Path + HttpContext.Request.QueryString });
            }

            var reportFileTypeList = DBCBAR.GetReportFileTypeList(userId);
            ViewBag.ReportFileTypeList = reportFileTypeList;

            if (reportFileType == null && reportFileTypeList.Count > 0)
                return RedirectToAction("CheckRules", new { reportFileType = reportFileTypeList[0].Value });

            var checkRulesList = new List<CheckRule>();
            if (reportFileTypeList.Count > 0)

                checkRulesList = DBCBAR.GetCheckRules(reportFileType, Status);
            ViewBag.Status = Status == null ? 1 : Status;
            return View(checkRulesList);

        }

        [HttpGet]
        public ActionResult Download(int id)
        {
            int? userId = HttpContext.Session.GetInt32("UserId") as int?;
            if (userId == null)
                return new EmptyResult();

            var downloadFileInfo = DBCBAR.GetDownload(id);

            if (downloadFileInfo.UPLOAD_FILE_DATA.Length == 0)
                return new EmptyResult();


            MemoryStream ms = new MemoryStream(downloadFileInfo.UPLOAD_FILE_DATA);
            var fsr = new FileStreamResult(ms, "application/vnd.ms-excel.sheet.macroEnabled.12");
            fsr.FileDownloadName = downloadFileInfo.Description;
            return fsr;
        }

        public ActionResult ReportTemplates()
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });
            ViewBag.Title = "Hesabat Formaları";
            var reportTemplates = DBCBAR.GetReportTemplates((int)userId);
            return View(reportTemplates);
        }

        public ActionResult DownloadReportTemplate(int id)
        {
            var userId = HttpContext.Session.GetInt32("UserId");
            if (userId == null)
                return new EmptyResult();

            Response.Headers.Add("Cache-Control", " no-store, no-cache");
            Response.Headers.Append("Pragma", "no-cache"); // HTTP 1.0.
            Response.Headers.Append("Expires", "0"); // Proxies.
            var rf = DBCBAR.GetReportTemplate(id);

            if (rf.NotFound)
                return new EmptyResult();

            MemoryStream ms = new MemoryStream(rf.Report_Template);
            string contentType = "application/vnd.ms-excel.sheet.macroEnabled.12";
            var fsr = new FileStreamResult(ms, contentType);
            fsr.FileDownloadName = rf.UPLOAD_FILE_NAME.EndsWith(".xls") || rf.UPLOAD_FILE_NAME.EndsWith(".xlsx") || rf.UPLOAD_FILE_NAME.EndsWith(".xlsm") ? rf.UPLOAD_FILE_NAME : rf.UPLOAD_FILE_NAME + ".xls";
            return fsr;
        }

        public ActionResult AddCheckRule(int? id)
        {
            int? userId = HttpContext.Session.GetInt32("UserId") as int?;
            if (userId == null)
            {
                var path = HttpContext.Request.Path;
                var query = HttpContext.Request.QueryString;
                var pathAndQuery = path + query;
                return RedirectToAction("Login", "Home", new { ReturnUrl = pathAndQuery });
            }

            var reportFileTypeList = DBCBAR.GetReportFileTypeList(userId);
            var reportFileTypeListForView = new List<SelectListItem>();
            reportFileTypeListForView.Add(new SelectListItem { Value = "0", Text = "Siyahıdan seçin" });
            foreach (var reportFileType in reportFileTypeList)
            {
                var reportFileTypeForView = new SelectListItem
                {
                    Text = reportFileType.Text,
                    Value = reportFileType.Value
                };
                reportFileTypeListForView.Add(reportFileTypeForView);
            }
            ViewBag.XlRuleOperators = new SelectList(Constants.XlRuleOperators, "Key", "Value");
            ViewBag.ReportFileTypes = reportFileTypeListForView;
            var reportSheets = new List<SelectListItem>();
            reportSheets.Add(new SelectListItem() { Text = "Siyahıdan seçin", Value = "0" });
            ViewBag.ReportSheets = reportSheets;
            ViewBag.RoundSize = "";
            var isEdit = 0;
            if (id != null)
            {
                isEdit = 1;
                var rule = new XlRule();
                rule.Id = int.Parse(id.ToString());
                var formula = DBCBAR.GetXlFormula(rule);
                ViewBag.FormulaCodeForView = formula.FormulaCodeForView;
                ViewBag.FormulaCode = formula.FormulaCode;
                ViewBag.FormulaText = rule.Formula;
                ViewBag.SplittedFormula = formula.splittedFormulaCodeForView;
                ViewBag.SplittedFormulaCode = formula.splittedFormulaCode;
                ViewBag.SplitOperators = formula.splitOperators;
                ViewBag.Status = formula.Status;
                ViewBag.RoundSize = rule.RoundSize;
                ViewBag.GroupName = formula.groupName;
            }
            ViewBag.IsEdit = isEdit;
            return View();
        }

        public JsonResult GetReportSheets(int id)
        {
            var reportTypes = DBCBAR.GetReportSheets(id);
            return Json(reportTypes);
        }

        public JsonResult GetReportCols(int id)
        {
            var reportCols = DBCBAR.GetReportColumns(id);
            return Json(reportCols);
        }

        public JsonResult GetReportRows(int id)
        {
            var reportRows = DBCBAR.GetReportRows(id);
            return Json(reportRows);
        }
        public JsonResult GetDataBySelectedReport(string reportFormula)
        {
            reportFormula = HttpUtility.UrlDecode(reportFormula.Substring(reportFormula.IndexOf('~') + 1));
            var reportData = DBCBAR.GetDataBySelectedReport(reportFormula);
            return Json(reportData);
        }

        public ActionResult AddOrUpdateFormula(int? id, XlRulesFormula formula)
        {
            var result = DBCBAR.AddOrUpdateXlRuleAndFormula(id, formula);
            if (result == 1)
            {
                string addText = "əlavə olundu";
                string updateText = "yeniləndi";
                if (id == null)
                {
                    TempData["SuccessMessage"] = "Yoxlama " + addText;
                }
                else
                {
                    TempData["SuccessMessage"] = "Yoxlama " + updateText;
                }

            }
            else
            {
                TempData["ErrorMessage"] = "Səhv baş verdi";
            }
            if (id == null)
            {
                return RedirectToAction("AddCheckRule");
            }
            else
            {
                return RedirectToAction("AddCheckRule", new { id = id });
            }
        }
    }
}

tedhiyye_portal_cbar/Views/Info/CheckRules.cshtml
@model List<CheckRule>

@{
    ViewBag.Title = "Yoxlamalar";
}


@section Currentpagelink
{
    <li><a href="javascript:void(0)">Məlumat</a></li>
    <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
    <li>
        @Html.ActionLink("Yoxlamalar", "CheckRules", "Info")
    </li>
}
<style>
    input, select, textarea {
        max-width: 100%;
    }
</style>
<div class="col-md-12 esahs-container-padd">
    <div class="row">
        <h1 class="pull-left" style="padding-left:15px">@ViewBag.Title</h1>
        <div class="pull-right" style="padding:15px">
            <button onclick="location.href='@Url.Action("AddCheckRule","Info")'" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            </button>
        </div>
    </div>


    <div class="form-horizontal" style="margin-top:20px;margin-bottom:20px;">
        @using (Html.BeginForm("CheckRules", "Info", FormMethod.Get))
        {
            <div class="row">
                <div class="col col-md-4">
                    <label>Hesabat növü</label>
                    <select name="reportFileType" class="form-control select2" style="width:100%" id="reportFileType">
                        <option value="-1">---</option>
                        @foreach (CustomSelectListItem customSelectList in (List<CustomSelectListItem>)ViewBag.ReportFileTypeList)
                        {
                            if (customSelectList.Value == Context.Request.Query["reportFileType"])
                            {

                                <option value="@customSelectList.Value" is-phqe="@customSelectList.Is_PHQE" selected>@customSelectList.Text</option>
                            }
                            else
                            {
                                <option value="@customSelectList.Value" is-phqe="@customSelectList.Is_PHQE">@customSelectList.Text</option>
                            }
                        }
                    </select>
                </div>
                <div class="col col-md-2 hidden">
                    <label>&nbsp;</label>
                    <input type="submit" value="Göstər" class="btn btn-primary" id="btShow" />
                </div>
                <div class="col col-md-2 pull-right">
                    <label>Status</label>
                    @{
                        var status = ViewBag.Status;
                        <select name="Status" id="Status" class="form-control select2">
                            <!option value="1" @(status == 1 ? "selected" : "")>Aktiv</!option>
                            <!option value="0" @(status == 0 ? "selected" : "")>Passiv</!option>
                        </select>
                    }
                </div>
                <div class="col col-md-2 hidden">
                    <label>&nbsp;</label>
                    <input type="submit" value="Göstər" class="btn btn-primary" id="btShow2" />
                </div>
            </div>
        }
    </div>

    <div class="table-responsive esahs-table">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th style="width:50px;text-align: center">
                        №
                    </th>
                    <th>
                        Formul
                    </th>
                    <th style="width:50px;text-align: center">Yenilə</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count == 0)
                {
                    <tr>
                        <td colspan="3" style="text-align: center">
                            Yoxlama yoxdur
                        </td>
                    </tr>
                }
                @for (var i = 0; i < Model.Count; i++)
                {
                    var item = Model[i];
                    <tr>
                        <td style="text-align: center">
                            @(i + 1)
                        </td>
                        <td>
                            @item.Formula
                        </td>
                        <td style="width:50px;text-align: center">
                            <button onclick="location.href='@Url.Action("AddCheckRule","Info",new { id=item.Id })'" class="btn btn-primary">
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

</div>

@section Scripts
{
    <script>
        $(function () {
            $('#reportFileType').change(function () {
                $('#btShow').click();
            });
            $('#Status').change(function () {
                $('#btShow2').click();
            });
        });
    </script>
}

tedhiyye_portal_cbar/Views/Info/Downloads.cshtml
@model List<DownloadFileInfo>


@section Currentpagelink
{
    <li><a href="javascript:void(0)">Məlumat</a></li>
    <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
    <li>
        @Html.ActionLink((string)ViewBag.Title, "Downloads", "Info")
    </li>
}
<style>
    input, select, textarea {
        max-width: 100%;
    }
</style>
<div class="col-md-12 esahs-container-padd">
    <h1>@ViewBag.Title</h1>
    @if (ViewBag.ShowDepartments)
    {
        <div class="form-horizontal" style="margin-top:20px;margin-bottom:20px;">
            @using (Html.BeginForm("Downloads", "Info", FormMethod.Get))
            {
                <div class="row">
                    <div class="col col-md-4">
                        <label>Departament</label>
                        @Html.DropDownList("department", (SelectList)ViewBag.DepartmentsList, "---", new { @class = "form-control select2" })
                    </div>
                    <div class="col col-md-2 hidden">
                        <label>&nbsp;</label>
                        <input type="submit" value="Göstər" class="btn btn-primary" id="btShow" />
                    </div>
                </div>
            }
        </div>
    }
    <div class="table-responsive esahs-table">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th style="vertical-align: middle">
                        Ad
                    </th>
                    <th style="vertical-align: middle">
                        Açıqlama
                    </th>
                    @if (ViewBag.ShowDepartments)
                    {
                        <th style="vertical-align: middle">
                            Departament
                        </th>
                        <th style="vertical-align: middle">
                            Şöbə
                        </th>
                    }
                    <th style="width:100px;vertical-align: middle">
                        Yüklə
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Head</td>
                            <td>
                                @item.Description
                            </td>
                            @if (ViewBag.ShowDepartments)
                            {
                                <td>
                                    @item.DepartmentName
                                </td>
                                <td>
                                    @item.SectionName
                                </td>
                            }
                            <td style="width:100px;text-align: center">
                                <a href="~/Info/Download/@item.Id"><i class="fa fa-download"></i> Yüklə</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">
                            Yükləmə yoxdur
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
{
    <script>
        $(function () {
            $('#department').change(function () {
                $('#btShow').click();
            });
        });
    </script>
}

tedhiyye_portal_cbar/Views/Info/ReportTemplates.cshtml
@model List<ReportFile>



@section Currentpagelink
{
    <li><a href="javascript:void(0)">Məlumat</a></li>
    <li><i class="fa fa-angle-right" aria-hidden="true"></i></li>
    <li>
        @Html.ActionLink((string)ViewBag.Title, "ReportTemplates", "Info")
    </li>
}
<style>
    input, select, textarea {
        max-width: 100%;
    }
</style>
<div class="col-md-12 esahs-container-padd">
    <h1>@ViewBag.Title</h1>
    <div class="table-responsive esahs-table">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th style="vertical-align: middle">
                        Hesabat
                    </th>
                    <th style="vertical-align: middle">
                        Period
                    </th>
                    <th style="vertical-align: middle">
                        Göndərilmə müddəti
                    </th>
                    <th style="vertical-align: middle">
                        Faylın adı
                    </th>
                    <th style="width:100px;vertical-align: middle">
                        Yüklə
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.REPORT_FILE_TYPE_NAME</td>
                            <td>
                                @item.Period
                            </td>
                            <td>
                                @item.SendTime
                            </td>
                            <td>
                                @item.UPLOAD_FILE_NAME
                            </td>
                            <td style="width:100px;text-align: center">
                                <a href="~/Info/DownloadReportTemplate/@item.ID"><i class="fa fa-download"></i> Yüklə</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">
                            Yükləmə yoxdur
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>