tedhiyye_portal_cbar/Controllers/HomeController.cs
using tedhiyye_portal_cbar.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using tedhiyye_portal_shared;
using tedhiyye_portal_shared.ViewModels;
using tedhiyye_portal_cbar;

namespace insurance_system_cbar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", new
                {
                    ReturnUrl = HttpContext.Request.Path + HttpContext.Request.QueryString
                });

            int userID = (int)HttpContext.Session.GetInt32("UserId");
            int departmentID = (int)HttpContext.Session.GetInt32("DepartmentId");

            if (!ToolsCBAR.HasRole(CBARUserRole.Bank_prudential))
            {
                if (ToolsCBAR.HasRole(CBARUserRole.Real_sector))
                    return RedirectToAction("Questionnaire", "RealSector");
                else
                    return RedirectToAction("ChangePassword", "Home");

            }

            var Reports = DBCBAR.GetRecentUploadedReportFiles(userID, -1, 10);
            ViewBag.Reports = Reports;

            var UnreadCount = DBCBAR.GetUnreadInboxMessagesCount(userID);
            ViewBag.UnreadCount = UnreadCount;

            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            UsernamePasswordVM up = new UsernamePasswordVM();
            return View(up);
        }

        [HttpPost]
        public ActionResult Login(UsernamePasswordVM up)
        {
            // For debug
            bool isDebug = false;
            if (HttpContext.Request.Path.Value.StartsWith("http://localhost"))
            {
                isDebug = true;
            }

            if (ModelState.IsValid || isDebug)
            {
                bool userExistsInDb = DBCBAR.CheckUserName(up.Username, out int userId, out int departmentid);

                if (!userExistsInDb)
                {
                    ViewBag.LoginMessage = "İstifadəçi adı sistemdə tapılmadı";
                    return View(up);
                }

                LdapLocal ldap = new LdapLocal();

                if (!ldap.NovellLogin(up.Username, up.Password, out LdapLocal.LDAPUser ldapUser))
                {
                    ViewBag.LoginMessage = "İstifadəçi məlumatları səhvdir və ya tapılmadı";
                    return View(up);
                }

                HttpContext.Session.SetInt32("DepartmentId", departmentid);
                HttpContext.Session.SetString("DepartmentName", ldapUser.Department);
                HttpContext.Session.SetInt32("UserId", userId);
                HttpContext.Session.SetString("Username", ldapUser.Username);
                HttpContext.Session.SetString("FullName", ldapUser.Displayname);
                HttpContext.Session.SetString("Roles", "");
                HttpContext.Session.SetString("RealSectorCompanyTypes", "");

                Log.Add("Login", string.Format("UserId: {0}, Username: {1}", userId, ldapUser.Username));

                if (HttpContext.Request.Query["ReturnUrl"].ToString() != null && Url.IsLocalUrl(HttpContext.Request.Query["ReturnUrl"].ToString()))
                    return Redirect(HttpContext.Request.Query["ReturnUrl"].ToString());
                else
                    return RedirectToAction("Index", "Home");
            }
            return View(up);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            Log.Add("Logout", string.Format("UserId: {0}, Username: {1}", HttpContext.Session.GetInt32("UserId"), HttpContext.Session.GetInt32("Username")));

            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult ConvertAllToHash()
        {
            DBCBAR.ConvertAllToHash();
            return RedirectToAction("Index");
        }

        [HttpGet]
        [HttpPost]
        public ActionResult Error()
        {
            return View();
        }

        public class LDAPUser
        {
            public string LastName { get; set; }
            public string Firstname { get; set; }
            public string Email { get; set; }
            public string Username { get; set; }
            public string Department { get; set; }
            public string Position { get; set; }
        }
    }
}

tedhiyye_portal_cbar/Controllers/MessagesController.cs
using tedhiyye_portal_cbar.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace tedhiyye_portal_cbar.Controllers
{
    public class MessagesController : Controller
    {
        public ActionResult Inbox(int? page, int? message_id)
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });

            if (message_id != null)
            {
                DBCBAR.MarkInboxMessageAsRead(message_id.Value);
                var message = DBCBAR.GetInboxMessage(message_id.Value);
                ViewBag.Message = message;
            }

            var messagesInbox = DBCBAR.GetInboxMessages((int)HttpContext.Session.GetInt32("UserId"), page ?? 1, 5);
            return View(messagesInbox);
        }

        public ActionResult Sent(int? page, int? message_id)
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });

            if (message_id != null)
            {
                var message = DBCBAR.GetSentMessage(message_id.Value);
                ViewBag.Message = message;
            }

            var messagesSent = DBCBAR.GetSentMessages(0, (int)HttpContext.Session.GetInt32("DepartmentId"), page ?? 1, 5);
            return View(messagesSent);
        }

        [HttpGet]
        public ActionResult Compose()
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });

            ViewBag.DepartmentList = DBCBAR.GetBankListForSelectBox((int)HttpContext.Session.GetInt32("UserId"));

            var composeMessageVM = new ComposeMessageVM();
            return View(composeMessageVM);
        }

        [HttpPost]
        public ActionResult Compose(ComposeMessageVM composeMessageVM)
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });

            bool sent = false;

            if (ModelState.IsValid)
            {
                sent = DBCBAR.SendMessage(0, composeMessageVM);
            }

            if (sent)
            {
                TempData["SuccessMessage"] = "Mesaj göndərildi";
                return RedirectToAction("Sent");
            }
            else
            {
                ViewBag.DepartmentList = DBCBAR.GetBankListForSelectBox((int)HttpContext.Session.GetInt32("UserId"));

                return View(composeMessageVM);
            }
        }
    }
}

tedhiyye_portal_cbar/Controllers/StatReportsController.cs
using tedhiyye_portal_cbar.Models;
using tedhiyye_portal_cbar.ViewModels;
using tedhiyye_portal_shared;
using tedhiyye_portal_shared.Domains;
using tedhiyye_portal_shared.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using tedhiyye_portal_cbar;

namespace tedhiyye_portal_cbar.Controllers
{
    [DisableRequestSizeLimit]
    public class StatReportsController : Controller
    {

        [HttpGet]
        public ActionResult Index(string[] bankType, int[] bank_ids, string yearmonth = "", string days = "", string status = "", string report_file_type_id = "")
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });

            int? userId = HttpContext.Session.GetInt32("UserId") as int?;

            ViewBag.ReportFileTypeList = DBCBAR.GetReportFileTypeList(userId);

            SetFilterViewBags(bankType, bank_ids);

            if (!IfParamsIsEmpty(ref yearmonth, bank_ids, days))
                return Redirect(String.Format("~/StatReports?yearmonth={1}&days=", bankType, yearmonth));

            ViewBag.YearMonthFilterValidation = "";
            if (HttpContext.Request.Query["yearmonth"].Count != 0)
            {
                if (HttpContext.Request.Query["yearmonth"].ToString() == "")
                    ViewBag.YearMonthFilterValidation = "İl-Ay seçilməlidir";
            }

            var Reports = new List<Report>();
            ViewBag.ShowTable = true;
            if (yearmonth != "")
            {
                string[] parts = yearmonth.Split('-');
                int year = Convert.ToInt32(parts[0]);
                int month = Convert.ToInt32(parts[1]);
                int daysCount = Convert.ToInt32(days);

                var DaysListinCurrentMonth = new List<SelectListItem>();

                for (int i = 1; i <= DateTime.DaysInMonth(year, month); i++)
                {
                    DaysListinCurrentMonth.Add(new SelectListItem { Text = "" + i, Value = "" + i });
                }

                ViewBag.DaysListinCurrentMonth = DaysListinCurrentMonth;

                Reports = DBCBAR.GetReports(ConvertToBankTypeFilter(bankType), bank_ids, userId.Value, year, month, days, status, report_file_type_id);
                ViewBag.CheckAllVisible = true;
            }
            else
            {
                ViewBag.ShowTable = false;
                ViewBag.CheckAllVisible = false;
            }
            ViewBag.Reports = Reports;

            if (bank_ids == null || bank_ids.Length == 0)
                ViewBag.CheckAllDisabled = true;
            else
            {
                var PeriodEndDates = Tools.GetYearMonthEndDates(yearmonth, days);
                ViewBag.PeriodEndDates = String.Join(",", PeriodEndDates.Select(d => d.ToString("yyyy-MM-dd")));
                ViewBag.CheckAllDisabled = false;
            }

            ActionVM actionVM = new ActionVM();
            return View(actionVM);
        }

        public ReportActionMessageVM DoReportOperation(string tbId, string tbAction)
        {
            ReportActionMessageVM message = new ReportActionMessageVM();
            string success = "";
            string error = "";
            List<int> idsWithError = new List<int>();
            List<int> idsWithSimilar = new List<int>();

            if (tbAction == "confirmascorrect")
            {
                //var report = reportsInGroup.FirstOrDefault(x => x.ID == actionVM.Id);
                var similarReportExist = DBCBAR.CheckConfirmedAsCorrectSimilarReports(Convert.ToInt32(tbId));
                if (similarReportExist)
                {
                    error = "Səhv! Hesabat düz kimi qəbul edilmədi";
                    error += ". ID " + tbId + " hesabatı ilə eyni tip, period və statistik vahidə aid başqa düzdür olan hesabat var.";
                    DBLog.AddError("ConfirmAsCorrectReport", HttpContext, tbId, "has similar other correct report");
                }
                else
                {
                    bool p_result;
                    string p_result_message;
                    p_result = DBCBAR.ConfirmAsCorrect(Convert.ToInt32(tbId), out p_result, out p_result_message);
                    if (p_result)
                    {
                        success = p_result_message;
                        DBLog.AddInfo("ConfirmAsCorrectReport", HttpContext, tbId);
                    }
                    else
                    {
                        error = "Səhv! hesabat düz kimi qəbul edilmədi";
                        DBLog.AddError("ConfirmAsCorrectReport", HttpContext, tbId);
                    }
                }

                message.Error = error;
                message.Success = success;
                return message;

            }
            else if (tbAction == "confirm")
            {
                //var report = reportsInGroup.FirstOrDefault(x => x.ID == actionVM.Id);
                var similarReportExist = DBCBAR.CheckConfirmedAsCorrectSimilarReports(Convert.ToInt32(tbId));
                if (similarReportExist)
                {
                    error = "Səhv! Hesabat düz kimi qəbul edilmədi";
                    error += ". ID " + tbId + " hesabatı ilə eyni tip, period və statistik vahidə aid başqa düzdür olan hesabat var.";
                    DBLog.AddError("ConfirmAsCorrectReport", HttpContext, tbId, "has similar other correct report");
                }
                else
                {
                    bool p_result;
                    string p_result_message;
                    p_result = DBCBAR.ConfirmCorrect(Convert.ToInt32(tbId), out p_result, out p_result_message);
                    if (p_result)
                    {
                        success = p_result_message;
                        DBLog.AddInfo("ConfirmAsCorrectReport", HttpContext, tbId);
                    }
                    else
                    {
                        error = "Səhv! hesabat düz kimi qəbul edilmədi";
                        DBLog.AddError("ConfirmAsCorrectReport", HttpContext, tbId);
                    }
                }

                message.Error = error;
                message.Success = success;
                return message;
            }
            else if (tbAction == "cancel")
            {

                if (idsWithError.Count > 0)
                {
                    error = "Səhv! ID " + String.Join(", ", idsWithError) + " hesabat(lar)ından imtina alınmadı";
                }
                else
                {
                    bool p_result;
                    string p_result_message;
                    p_result = DBCBAR.CancelReport(Convert.ToInt32(tbId), out p_result, out p_result_message);
                    if (p_result)
                    {
                        success = p_result_message;
                    }
                    else
                    {
                        error = "Səhv! hesabat düz kimi qəbul edilmədi";
                    }
                }
                message.Error = error;
                message.Success = success;
                return message;
            }
            else
            {
                message.Error = "";
                message.Success = "";
                return message;
            }
        }

        public ActionResult PerformActionReport(string tbId, string tbAction)
        {
            var resultMessage = DoReportOperation(tbId, tbAction);
            TempData["ErrorMessage"] = resultMessage.Error;
            TempData["SuccessMessage"] = resultMessage.Success;
            return View();
        }

        [HttpPost]
        public ActionResult Index(ActionVM actionVM, string[] bankType, int[] bank_ids, string yearmonth = "", string days = "", string status = "")
        {
            if (HttpContext.Session.GetInt32("UserId") == null)
                return RedirectToAction("Login", "Home", new { ReturnUrl = Request.Path + Request.QueryString });

            SetFilterViewBags(bankType, bank_ids);

            if (Tools.IsLunchBreak(DateTime.Now))
            {
                DBLog.AddError("ChangeReportStatus", HttpContext, actionVM.Id.ToString(), "cannot change report status in lunch break");
                TempData["ErrorMessage"] = "Səhv! Nahar fasiləsində (13:00-14:00) status dəyişikliyi etmək olmaz.";

                return Redirect(HttpContext.Request.Path + HttpContext.Request.QueryString);
            }

            List<int> idsWithError = new List<int>();
            List<int> idsWithSimilar = new List<int>();


            if (actionVM.Action == "confirmascorrect")
            {
                var resultMessage = DoReportOperation(actionVM.Id.ToString(), actionVM.Action);
                TempData["ErrorMessage"] = resultMessage.Error;
                TempData["SuccessMessage"] = resultMessage.Success;

                return Redirect(HttpContext.Request.Path + HttpContext.Request.QueryString);
            }
            else if (actionVM.Action == "cancel")
            {

                var resultMessage = DoReportOperation(actionVM.Id.ToString(), actionVM.Action);
                TempData["ErrorMessage"] = resultMessage.Error;
                TempData["SuccessMessage"] = resultMessage.Success;

                return Redirect(HttpContext.Request.Path + HttpContext.Request.QueryString);
            }
            else
            {
                return Redirect(HttpContext.Request.Path + HttpContext.Request.QueryString);
            }
        }

        [HttpGet]
        public ActionResult UploadReport(string[] bank_types, string BankId)
        {

tedhiyye_portal_cbar/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Ana səhifə";
}

@section Currentpagelink
{
    <li>
        @Html.ActionLink("Ana səhifə", "Index")
    </li>
}
<style>
    @@media (min-width: 992px) {
        .panel-help .panel-body {
            min-height: 330px;
        }
    }

    @@media (min-width: 1366px) {
        .panel-help .panel-body {
            min-height: 230px;
        }
    }

    @@media (min-width: 1600px) {
        .panel-help .panel-body {
            min-height: 210px;
        }
    }

    @@media (min-width: 1900px) {
        .panel-help .panel-body {
            min-height: 160px;
        }
    }

    @@media (min-width: 1250px) {
        #divActionLogs .modal-dialog {
            width: 1200px;
        }
    }

    @@media (min-width: 1350px) {
        #divActionLogs .modal-dialog {
            width: 1300px;
        }
    }
</style>
<div class="col-md-12 esahs-container-padd">
    <h1>@ViewBag.Title</h1>

    @if (ViewBag.UnreadCount > 0)
    {
        <div class="alert alert-warning" role="alert">
            Sizin @ViewBag.UnreadCount oxunmamış bildirişiniz var. <a href="@Url.Action("Inbox", "Messages")">Bildirişlərə keç</a>
        </div>
    }

    <div class="row">
        <div class="col col-md-12">
            <div>
                <h2 class="pull-left">Son hesabatlar</h2>
                <a href="@Url.Action("Index", "StatReports")" class="pull-right" style="margin-top:30px;">Hesabat arxivi</a>
            </div>
            <div class="clearfix"></div>
            <div class="table-responsive esahs-table">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th>Hesabat tipi</th>
                            <th>Statistik Vahid</th>
                            <th>Yüklənmə vaxtı</th>
                            <th>Hesabat dövrü</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (((List<UploadedReportFile>)ViewBag.Reports).Count == 0)
                        {
                            <tr>
                                <td colspan="6">
                                    <div style="text-align:center;position:absolute; min-width:100%;">Cədvəldə heç bir hesabat yoxdur</div>
                                    &nbsp;
                                </td>
                            </tr>
                        }
                        @foreach (var item in (List<UploadedReportFile>)ViewBag.Reports)
                        {
                            <tr>
                                <td style="width:100px;white-space:nowrap;text-align:center;">
                                    @if (item.ID != 0)
                                    {
                                        <a class="btn btn-default" href="@Url.Action("DownloadReport", "StatReports", new { id = item.ID })" title="Hesabat Excel faylını yüklə">
                                            <i aria-hidden="true" class="fa fa-download"></i>
                                        </a>
                                    }
                                    <a class="btn btn-default" href="javascript:void(0)" onclick="ShowActionLogs(@item.ID)" title="Əməliyyat tarixçəsi">
                                        <span class="bt_cl1 bt1-green">
                                            <i aria-hidden="true" class="fa fa-history"></i>
                                        </span>
                                    </a>
                                </td>
                                <td>@item.REPORT_FILE_TYPE_NAME</td>
                                <td>@item.BANK</td>
                                <td>@item.UPLOAD_TIME.ToString("dd.MM.yyyy HH:mm")</td>
                                <td>@item.PERIODSTART.Value.ToString("dd.MM.yyyy") - @item.PERIODEND.Value.ToString("dd.MM.yyyy")</td>
                                <td>
                                    @if (Constants.ErrorListShownForStatuses.Contains((ReportStatus)item.REPORT_FILE_STATUS_ID))
                                    {
                                        <a href="javascript:void(0)" onclick="ShowReportErrors(@item.ID)">
                                            @if (Tools.IsLoadingUploadFileStatus((ReportUploadFileStatus)item.REPORT_FILE_STATUS_ID))
                                            {
                                                <img src="~/cbar/images/ajax-loader.gif" />
                                            }
                                            <span class="@Tools.GetReportUploadFileStatusCssClass(item.REPORT_FILE_STATUS_ID)">@item.STATUS</span>
                                        </a>
                                    }
                                    else
                                    {
                                        @if (Tools.IsLoadingUploadFileStatus((ReportUploadFileStatus)item.REPORT_FILE_STATUS_ID))
                                        {
                                            <img src="~/cbar/images/ajax-loader.gif" />
                                        }
                                        <span class="@Tools.GetReportUploadFileStatusCssClass(item.REPORT_FILE_STATUS_ID)">@item.STATUS</span>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row" style="margin-top:20px;">
        <div class="col col-md-4">
            <div class="panel panel-default panel-help">
                <div class="panel-heading"><i class="fa fa-file-text"></i> Hesabatlar</div>
                <div class="panel-body">
                    Hesabatlar bölməsində təyin olunmuş formalar vasitəsi ilə statistik məlumatlarının göndərilməsi həyata keçirilir. Həmçinin bu bölmədə hesabat arxivi vasitəsi ilə göndərilən məlumatların yoxlanılması və statusların izlənilməsi aparılır.
                </div>
            </div>
        </div>
        <div class="col col-md-4">
            <div class="panel panel-default panel-help">
                <div class="panel-heading"><i class="fa fa-university"></i> Statistik Vahidlər</div>
                <div class="panel-body">
                    <ul>
                        <li>Hesabatlar - bu bölmədə statistik vahidlər üzrə hesabatların icmal cədvəli təqdim edilir və buradan məlumatların BI sisteminə yayımlanması həyat keçirilir</li>
                        <li>Məsul şəxslər - bu bölmədə statistik vahid və hesabatlar üzrə məsul şəxslərin cədvəli təqdim edilir, həmçinin cədvəlin Excel faylına eksport imkanı verilir.</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col col-md-4">
            <div class="panel panel-default panel-help">
                <div class="panel-heading"><i class="fa fa-file-text"></i> Daxili hesabatlar</div>
                <div class="panel-body">
                    Bu bölmədə Mərkəzi Bankın daxili hesabatlarının idarəedilməsi aparılır.
                    <ul>
                        <li>Maliyyə indikatorları - hesabatlar arxivi və hesabatların daxil edilməsi</li>
                        <li>Məzənnə - məzənnə avtomatik olaraq cbar.az saytından yüklənilir (həm günlük, həm aylıq)</li>
                        <li>Bloomberg - hesabatlar arxivi və hesabatların daxil edilməsi</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col col-md-4">
            <div class="panel panel-default panel-help">
                <div class="panel-heading"><i class="fa fa-envelope"></i> Bildirişlər</div>
                <div class="panel-body">
                    Bildirşlər vasitəsi ilə Mərkəzi Bank və statistik vahidlər arasında elektron məlumat mübadiləsi təmin edilir. Statistik hesabatlarda dəyişikliklər, hesabatlar üzrə gecikmələr və digər mövzularla bağlı statistik vahidlər məlumatlandırılır.
                </div>
            </div>
        </div>
        <div class="col col-md-4">
            <div class="panel panel-default panel-help">
                <div class="panel-heading"><i class="fa fa-info-circle"></i> Məlumat</div>
                <div class="panel-body">
                    Məlumat bölməsində statistik hesabatların formaları, hesabatların yoxlamaları, Mərkəzi Bank və statistik vahidlərin məsul şəxsləri, normativ-hüquqi baza, və istifadəçi təlimatı üzrə statistik vahidlərə məlumatlar təqdim olunur.
                </div>
            </div>
        </div>
        <div class="col col-md-4">
            <div class="panel panel-default panel-help">
                <div class="panel-heading"><i class="fa fa-sliders"></i> Konfiqurasiya</div>
                <div class="panel-body">
                    Konfiqurasiya bölməsində elektron imza istifadəsi üçün Səlahiyyətlərin ötürülməsi həyata keçirilə bilər və istifadəçi profilində dəyişikliklər edilə bilər.
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="divReportErrors" role="dialog">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Səhvlər</h3>
            </div>
            <div class="modal-body">
                <iframe id="ifReportErrors" frameborder="0" src="about:blank" width="100%" height="500px"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Bağla</button>
            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="divActionLogs" role="dialog">
    <div class="modal-dialog modal-lg">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Əməliyyat tarixçəsi</h3>
            </div>
            <div class="modal-body">
                <iframe id="ifActionLogs" frameborder="0" src="about:blank" width="100%" height="500px"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Bağla</button>
            </div>
        </div>

    </div>
</div>
@section Scripts
{
    <script>
        function ShowReportErrors(reportId, checkId) {
            $('#ifOpNotes').attr('src', "about:blank");
            $('#divReportErrors').modal();

            setTimeout(function () {
                $('#divReportErrors .modal-title').text('Səhvlər (ID: ' + reportId + ')');
                $('#ifReportErrors').attr('src', "StatReports/ReportErrors?reportId=" + reportId);
            }, 100);
            return false;
        }

        function ShowActionLogs(id) {
            $('#ifOpNotes').attr('src', "about:blank");
            $('#divActionLogs').modal();

            setTimeout(function () {
                $('#divActionLogs .modal-title').text('Əməliyyat tarixçəsi (ID: ' + id + ')');
                $('#ifActionLogs').attr('src', "StatReports/ActionLogs/" + id);
            }, 100);
            return false;
        }
    </script>
}

tedhiyye_portal_cbar/Views/Home/Login.cshtml
@model UsernamePasswordVM

@{
    ViewBag.Title = "GİRİŞ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Currentpagelink
{
    <li>
        @Html.ActionLink("Giriş", "Login")
    </li>
}

<style>
    .form-horizontal .control-label {
        padding-top: 0;
    }

    .form-horizontal h4 {
        margin-top: 30px;
        color: #888;
    }

    .form-horizontal hr {
        margin-top: 0;
    }
</style>
<div class="container card user-page">
    <div class="row">
        <div class="col-md-12" id="title">
            <p class="title"><span>@ViewBag.Title</span></p>
        </div>
    </div>
    <div class="row row-margin">
        <div class="col-md-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <br />
                    @ViewBag.Info
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-3 col-md-offset-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @style = "width: 200px;" } })
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-3 col-md-offset-2" })
                        <div class="col-md-5">
                            @Html.PasswordFor(model => model.Password, new { @class = "form-control", @maxlength = "50", @style = "width: 200px;" })                           @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-5 col-md-5">
                            <input id="btLogin" type="submit" value="Daxil ol" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    @if (ViewBag.LoginMessage != null)
    {
        <div class="alert alert-danger" style="font-size: larger;text-align:center;margin-top: 20px;">
            @ViewBag.LoginMessage
        </div>
    }

</div>

@section Scripts
{
    <script>
        $(function () {
            $('#Username').focus();
        });
    </script>
}